before_script:
- 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
- chmod 644 ~/.ssh/known_hosts
depoy_staging:
  stage: deploy
  script:
   - ssh -o StrictHostKeyChecking=no imensoss@164.52.209.16 "cd /home/imensoss/ultron.imenso.in && git checkout staging && git pull origin staging && exit"
  only:
   - staging
